### ISSUE TITLE
响应码 500错误

### ISSUE THREAD

**Issue by sblvbon** [opq-osc/bot_exhentai#1]
<img width="301" alt="屏幕截图 2022-04-26 133224" src="https://user-images.githubusercontent.com/91000365/165228608-a72244ee-5e18-4380-9a18-34329bd740e3.png">
上传指令无法执行

**Comment by yuban10703** [comment]
可能是风控了?
把OPQ的相关日志也截下

**Comment by sblvbon** [comment]
确认没有风控

**Comment by sblvbon** [comment]
而且应该回复“下载中”和“上传中”都没有，但文件下载正常，压缩正常

**Comment by yuban10703** [comment]
那应该是风控了,过几天说不定就好了

**Comment by sblvbon** [comment]
<img width="526" alt="image" src="https://user-images.githubusercontent.com/91000365/165231828-2905acd8-abd7-403d-ac5e-a9decc43dc43.png">
到这里就没反应了，日志里就是响应码 500错误

**Comment by sblvbon** [comment]
不是风控，图片和文件发送都正常

**Comment by yuban10703** [comment]
看看OPQ的相关日志

**Comment by sblvbon** [comment]
<img width="347" alt="image" src="https://user-images.githubusercontent.com/91000365/165232310-87b07c00-65bb-4615-92d4-27b3db9fe3c2.png">

啊这，咋啥都没有

**Comment by yuban10703** [comment]
> 不是风控，图片和文件发送都正常

你是怎么得出文件发送正常的.......

**Comment by sblvbon** [comment]
部署有色图bot（
至少色图bot一切正常

**Comment by yuban10703** [comment]
要不你换个群再试试...

**Comment by sblvbon** [comment]
> 要不你换个群再试试...

试过了

**Comment by sblvbon** [comment]
<img width="443" alt="image" src="https://user-images.githubusercontent.com/91000365/165232927-932fec7f-2c65-4f70-8d4b-8b96811c4700.png">
OPQ日志

**Comment by yuban10703** [comment]
你更新下python的包到最新再试试...

**Comment by sblvbon** [comment]
行

**Comment by sblvbon** [comment]
python3.9.2够新了吗

**Comment by yuban10703** [comment]
不是,是更新pip的包...

pip3 install -r requirements.txt --upgrade

**Comment by sblvbon** [comment]
emmm，还是一样的错误

**Comment by yuban10703** [comment]
等我晚上看看吧...

**Comment by yuban10703** [comment]
我试了下,没问题啊

**Comment by yuban10703** [comment]
![Screenshot_2022-04-26-20-51-59-591_com tencent mo](https://user-images.githubusercontent.com/39484884/165303947-b664c31c-eb6f-4720-8b61-fd78df054e64.jpg)

**Comment by sblvbon** [comment]
我重新部署试试

**Comment by sblvbon** [comment]
所以大佬知道响应码 500是啥意思嘛

**Comment by sblvbon** [comment]
<img width="388" alt="image" src="https://user-images.githubusercontent.com/91000365/165413624-5f333403-f459-4126-bf65-432a154babe9.png">
<img width="368" alt="image" src="https://user-images.githubusercontent.com/91000365/165413719-5ec91987-01fd-48a0-a997-4b8cb3c5f123.png">
这些都没有被正常执行

**Comment by yuban10703** [comment]
被执行了,响应码500就是OPQ返回的

**Comment by sblvbon** [comment]
会不会是API更改过了的原因

**Comment by yuban10703** [comment]
最近没改API

我这里不能复现

**Comment by sblvbon** [comment]
已解决，原因是botoy中的QQ号没改成bot的QQ号，建议在README中说明
谢谢大佬
