### ISSUE TITLE
下载时出现 AttributeError: 'NoneType' object has no attribute 'group' 报错

### ISSUE THREAD

**Issue by emtsaikou** [opq-osc/bot_exhentai#2]
![image](https://user-images.githubusercontent.com/59403640/165703309-6b91a78e-e978-49d1-a987-c7afd07abe88.png)

**Comment by yuban10703** [comment]
可能是有些本子不能下载吧,没处理这部分

**Comment by emtsaikou** [comment]
我试了好多，都是这个报错

**Comment by yuban10703** [comment]
你用你的账号上ex,选个本子,点archiver download,看看界面是什么样子

**Comment by emtsaikou** [comment]
![image](https://user-images.githubusercontent.com/59403640/165743544-151c962e-4bae-4ec1-95e7-560a9eabf8c3.png)
这样的

**Comment by emtsaikou** [comment]
好像是需要积分和专门浏览器的意思

**Comment by yuban10703** [comment]
你点一下下载试试,是不是因为你积分不够了?..

**Comment by emtsaikou** [comment]
应该是因为积分不够，他提示我了

**Comment by emtsaikou** [comment]
还专门麻烦你了，实在不好意思

**Comment by yuban10703** [comment]
OK
