### ISSUE TITLE
求教，一些配置的问题

### ISSUE THREAD

**Issue by MokouTyan** [opq-osc/bot_exhentai#3]
目前的情况是OPQBOT已经运行了
![image](https://user-images.githubusercontent.com/40456395/168526400-13f12626-f677-41d7-a7c4-1f59aa3b718e.png)
requirement里面的依赖也安装了
![image](https://user-images.githubusercontent.com/40456395/168526471-6dc8e180-3196-4587-b81c-851d1857eda2.png)
botoy.json我放在该项目的目录下
![image](https://user-images.githubusercontent.com/40456395/168526621-22cc907e-7349-4691-bedd-359f677d9c30.png)
文件内是这么写的
![image](https://user-images.githubusercontent.com/40456395/168526841-8c9f7c39-7f45-4bae-9bff-2670ae7d8acc.png)
运行python3 exhentai.py出错
![image](https://user-images.githubusercontent.com/40456395/168526956-e95059b5-73fa-4194-a9dc-3d6b33b280ec.png)
网上查了一圈，不是很理解哪里出错了，所以请教一下，谢谢

**Comment by MokouTyan** [comment]
@yuban10703

**Comment by yuban10703** [comment]
不是这么运行的啊...

**Comment by yuban10703** [comment]
这是botoy的插件
你要丢到这个种路径下,然后启动bot.py才行
https://github.com/opq-osc/OPQ-SetuBot/tree/master/plugins

**Comment by MokouTyan** [comment]
> 这是botoy的插件 你要丢到这个种路径下,然后启动bot.py才行 https://github.com/opq-osc/OPQ-SetuBot/tree/master/plugin

肥肠感谢，我尝试一下~

**Comment by MokouTyan** [comment]
> 这是botoy的插件 你要丢到这个种路径下,然后启动bot.py才行 https://github.com/opq-osc/OPQ-SetuBot/tree/master/plugins

我现在目录改好了
![image](https://user-images.githubusercontent.com/40456395/168530539-55b095b6-3515-44fc-8505-c9e16ee04402.png)
botoy.json文件我放在了OPQ-SetuBot目录下，内容如下
![image](https://user-images.githubusercontent.com/40456395/168530895-8eb10174-b836-478c-8b52-83e7c3b7ca54.png)

运行仍然报错，是哪里做得不对吗？
![image](https://user-images.githubusercontent.com/40456395/168530795-45e8efd2-a7e7-4d16-8f0e-b239e841edfb.png)

**Comment by MokouTyan** [comment]
OPQ-SetuBot和该项目的requirement的依赖均已安装完毕

**Comment by yuban10703** [comment]
![image](https://user-images.githubusercontent.com/39484884/168531346-115ccc23-c059-4e36-84da-cb08d6257f5f.png)
把-main删掉

**Comment by MokouTyan** [comment]
运行成功了，感谢开发！
